version: "3.9"

services:
  productapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-products:latest
    container_name: api-products-container
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    depends_on:
      - mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - D:\uploads:/app/uploads
  
  mongo:
    image: mongo:4.4
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: DB_USER
      MONGO_INITDB_ROOT_PASSWORD: DB_PASSWORD 

    ports:
      - "27017:27017"  
    volumes:    
      - mongo-data:/data/db

volumes:
  mongo-data: